import type { NextPage } from 'next';
import Head from 'next/head';
import Setupage from '../components/setupage';

const Home: NextPage = () => {
  return (
    <div>
      <Setupage />
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>Hello</div>
      <footer>
        <div>This is the footer</div>
      </footer>
    </div>
  );
};

export default Home;
